import '../models/post.dart';


List<Post> getMockPosts() {
  return [
    Post(
      username: 'AnimeFan123',
      profileImage: 'https://picsum.photos/150/150?random=5',
      timestamp: '2h ago',
      content: 'Just finished Demon Slayer S3! Mind-blowing animation!',
      imageUrl: 'https://picsum.photos/400/200?random=100',
      likes: 42,
      comments: 8,
    ),
    Post(
      username: 'CosplayQueen',
      profileImage: 'https://picsum.photos/150/150?random=6',
      timestamp: '5h ago',
      content: 'Working on my Naruto cosplay. Any tips?',
      likes: 15,
      comments: 3,
    ),
    Post(
      username: 'MangaLad',
      profileImage: 'https://picsum.photos/150/150?random=7',
      timestamp: '1d ago',
      content: 'One Piece chapter 1089 was epic!',
      likes: 67,
      comments: 12,
    ),
    Post(
      username: 'ShonenStar',
      profileImage: 'https://picsum.photos/150/150?random=8',
      timestamp: '3h ago',
      content: 'Attack on Titan finale was intense! Thoughts?',
      imageUrl: 'https://picsum.photos/400/200?random=101',
      likes: 55,
      comments: 10,
    ),
    Post(
      username: 'KawaiiChan',
      profileImage: 'https://picsum.photos/150/150?random=9',
      timestamp: '6h ago',
      content: 'Just got my Sailor Moon merch! 🌙 So excited!',
      imageUrl: 'https://picsum.photos/400/200?random=102',
      likes: 28,
      comments: 5,
    ),
    Post(
      username: 'SenpaiVibes',
      profileImage: 'https://picsum.photos/150/150?random=10',
      timestamp: '8h ago',
      content: 'Who’s your favorite Jujutsu Kaisen character? Mine’s Gojo!',
      likes: 33,
      comments: 7,
    ),
    Post(
      username: 'NinjaNerd',
      profileImage: 'https://picsum.photos/150/150?random=11',
      timestamp: '10h ago',
      content: 'Rewatching Bleach for the nostalgia. Still hits hard!',
      imageUrl: 'https://picsum.photos/400/200?random=103',
      likes: 19,
      comments: 4,
    ),
    Post(
      username: 'AnimeArtLover',
      profileImage: 'https://picsum.photos/150/150?random=12',
      timestamp: '12h ago',
      content: 'Drew a fanart of Levi Ackerman. Should I post it?',
      likes: 45,
      comments: 9,
    ),
    Post(
      username: 'TokyoGhoulFan',
      profileImage: 'https://picsum.photos/150/150?random=13',
      timestamp: '1d ago',
      content: 'Tokyo Ghoul’s OST is hauntingly beautiful!',
      likes: 30,
      comments: 6,
    ),
    Post(
      username: 'ChibiMaster',
      profileImage: 'https://picsum.photos/150/150?random=14',
      timestamp: '1d ago',
      content: 'Planning a My Hero Academia watch party. Who’s in?',
      imageUrl: 'https://picsum.photos/400/200?random=104',
      likes: 50,
      comments: 11,
    ),
    Post(
      username: 'MoeMoeKyun',
      profileImage: 'https://picsum.photos/150/150?random=15',
      timestamp: '2d ago',
      content: 'Just started Haikyuu!! Why didn’t I watch this sooner?',
      likes: 25,
      comments: 3,
    ),
    Post(
      username: 'DragonBallZFan',
      profileImage: 'https://picsum.photos/150/150?random=16',
      timestamp: '2d ago',
      content: 'Goku vs. Vegeta is still the best fight ever!',
      imageUrl: 'https://picsum.photos/400/200?random=105',
      likes: 60,
      comments: 15,
    ),
    Post(
      username: 'CosplayKing',
      profileImage: 'https://picsum.photos/150/150?random=17',
      timestamp: '3d ago',
      content: 'My Luffy cosplay is almost done! Straw Hat vibes!',
      imageUrl: 'https://picsum.photos/400/200?random=106',
      likes: 38,
      comments: 7,
    ),
    Post(
      username: 'AnimeMemeLord',
      profileImage: 'https://picsum.photos/150/150?random=18',
      timestamp: '3d ago',
      content: 'When your favorite anime gets a bad adaptation 😭',
      likes: 22,
      comments: 4,
    ),
    Post(
      username: 'YuriFanatic',
      profileImage: 'https://picsum.photos/150/150?random=19',
      timestamp: '4d ago',
      content: 'Yuri on Ice deserves a second season! Who agrees?',
      likes: 40,
      comments: 8,
    ),
  ];
}

