// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjQ0WJerqYQF9TvN0KOIJYjUozmEcyOCY',
    appId: '1:509709123125:web:8a97d092323a77905bbb7c',
    messagingSenderId: '509709123125',
    projectId: 'amikiyo-6edab',
    authDomain: 'amikiyo-6edab.firebaseapp.com',
    storageBucket: 'amikiyo-6edab.firebasestorage.app',
    measurementId: 'G-RQQ6089852',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIPPFqVK0TnPlPSEswc-qHj7ATJJP_SLw',
    appId: '1:509709123125:android:51c40d438f953c1d5bbb7c',
    messagingSenderId: '509709123125',
    projectId: 'amikiyo-6edab',
    storageBucket: 'amikiyo-6edab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpKN2NFET52XGqUnEoaugFZf7c6seeiKw',
    appId: '1:509709123125:ios:49a950c8cf590b9e5bbb7c',
    messagingSenderId: '509709123125',
    projectId: 'amikiyo-6edab',
    storageBucket: 'amikiyo-6edab.firebasestorage.app',
    iosBundleId: 'com.example.amikiyo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpKN2NFET52XGqUnEoaugFZf7c6seeiKw',
    appId: '1:509709123125:ios:49a950c8cf590b9e5bbb7c',
    messagingSenderId: '509709123125',
    projectId: 'amikiyo-6edab',
    storageBucket: 'amikiyo-6edab.firebasestorage.app',
    iosBundleId: 'com.example.amikiyo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjQ0WJerqYQF9TvN0KOIJYjUozmEcyOCY',
    appId: '1:509709123125:web:c7e8b8abf85a45085bbb7c',
    messagingSenderId: '509709123125',
    projectId: 'amikiyo-6edab',
    authDomain: 'amikiyo-6edab.firebaseapp.com',
    storageBucket: 'amikiyo-6edab.firebasestorage.app',
    measurementId: 'G-E01088JD6K',
  );
}
